### ISSUE TITLE
error message：LLDB provided no error string

### ISSUE THREAD

**Issue by pei-wen-yang** [leokuo0724/drink-order-app#1]
已將Ｍach-O type 改為bundle
但還是出現下方錯誤訊息，請問該如何解決？

Could not attach to pid : “25274”
Domain: IDEDebugSessionErrorDomain
Code: 3
Failure Reason: LLDB provided no error string.
User Info: {
    DVTRadarComponentKey = 855031;
    RawLLDBErrorMessage = "LLDB provided no error string.";
}
--

**Comment by leokuo0724** [comment]
Mach-O 預設 Executable 應該可以正常執行。
想問改成 bundle 的原因是？

**Comment by pei-wen-yang** [comment]
預設Executable
會出現下方錯誤訊息
ld: entry point (_main) undefined. for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by leokuo0724** [comment]
程式碼有做什麼改動嗎？
可以檢查一下 AppDelegate.swift檔案上方的 @main 是否被刪除了
或者是重新 clone 再試試看

**Comment by pei-wen-yang** [comment]
我重新下載後發現是我自己在搞烏龍～
非常感謝你
我是swift菜鳥，最近想自己開發一個連結google sheet的ＡＰＰ～

**Comment by leokuo0724** [comment]
OK~ 沒問題
目前 README 沒有整理很完全，
如果串連 google sheet 的部分如果有問題，
可以參考這兩篇：
[串連菜單](https://medium.com/%E5%BD%BC%E5%BE%97%E6%BD%98%E7%9A%84-swift-ios-app-%E9%96%8B%E7%99%BC%E6%95%99%E5%AE%A4/ios-16-%E5%8F%AF%E4%B8%8D%E5%8F%AF%E9%A3%B2%E6%96%99%E8%A8%82%E8%B3%BCapp-part1-%E4%B8%B2%E9%80%A3-google-sheet-%E8%8F%9C%E5%96%AE-f72233f4aebf)
[SheetDB](https://medium.com/%E5%BD%BC%E5%BE%97%E6%BD%98%E7%9A%84-swift-ios-app-%E9%96%8B%E7%99%BC%E6%95%99%E5%AE%A4/ios-17-%E5%8F%AF%E4%B8%8D%E5%8F%AF%E9%A3%B2%E6%96%99%E8%A8%82%E8%B3%BCapp-part2-sheetdb-%E5%AD%98%E5%8F%96%E8%A8%82%E8%B3%BC%E6%B8%85%E5%96%AE%E8%B3%87%E6%96%99-d549976e45df)
